[package]
name = "web-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.4.0" }
config = "0.13.3"
deadpool-postgres = { version = "0.11.0", features = ["serde"] }
diesel = { version = "2.1.3", features = ["sqlite", "r2d2"] }
dotenvy = { version = "0.15.7" }
env_logger = "0.10.1"
log = { version = "0.4.20" }
serde = { version = "1.0.192", features = ["derive"] }
futures-util = "0.3.29"
derive_more="0.99.17"
uuid = { version = "1.5.0", features = ["serde", "v4"] }
