[package]
name = "web-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web.workspace = true
config = "0.13.3"
deadpool-postgres = { version = "0.11.0", features = ["serde"] }
diesel = { version = "2.1.3", features = ["postgres"] }
derive_more.workspace = true
dotenvy.workspace = true
env_logger.workspace = true
log.workspace = true
serde = { version = "1.0.192", features = ["derive"] }
uuid = { version="*", features = ["serde", "v4"] }
tokio-pg-mapper = { version = "0.2.0", features = ["serde"] }
tokio-pg-mapper-derive = { version = "0.2.0", features = ["serde"] }
tokio-postgres = { version = "0.7.6" }
